services:
  # App service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}
    expose:
      - "3000" # Expose internal port 3000 for Nginx reverse proxy
    volumes:
      # Mount CSV file into the app's public folder and make it available for download
      - ./public/mass_users_registeration_template_example.csv:/app/public/mass_users_registeration_template_example.csv
    depends_on:
      - postgres-db # Ensure Postgres is ready before the app starts
    networks:
      - app-network
    secrets:
      - db_user
      - db_password
      - db_name

  # PostgreSQL service
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
    ports:
      - "5432:5432" # Expose Postgres on port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    secrets:
      - db_user
      - db_password
      - db_name

  # Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Mount Let's Encrypt certificates to Nginx
      - ../certbot/idpmgr.cloud.cerist.dz/cert.pem:/etc/ssl/certs/fullchain.pem:ro
      - ../certbot/idpmgr.cloud.cerist.dz/key.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app # Nginx will only start after the app service is ready
      - certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/idpmgr.cloud.cerist.dz:/var/www/certbot 
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot -d idpmgr.cloud.cerist.dz --quiet; sleep 12h & wait $${!}; done;"
    networks:
      - app-network

# Define a custom network for services to communicate
networks:
  app-network:
    driver: bridge

# Volumes for persistent storage
volumes:
  postgres-data:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt