version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./package-lock.json:/app/package-lock.json:ro
      - .:/app
    command: npm run start
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgres://xxxx:xxxx@xxxx:5432/xxxx'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
      POSTGRES_DB: xxxx
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U xxxx -d xxxx -h 127.0.0.1 -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5
